language: elixir

sudo: false

# Erlang and Elixir default versions (overridden in some jobs).
elixir: 1.9.0
otp_release: 22.0

stages:
  - check formatted
  - test
  - check js

services:
  - xvfb

env:
  global:
    - MIX_ENV=test
    - NODE_VERSION="10.10.0"

cache:
  directories:
    - node_modules
    - deps

addons:
  firefox: "54.0"

jobs:
  include:
    - stage: test
      script:
        - mix test
        - bash test/prerelease.sh

    - elixir: 1.8.1
      otp_release: 21.2

    - elixir: 1.7.3
      otp_release: 19.3

    - stage: check formatted
      script: mix format --check-formatted
      before_install: skip

    - stage: check js
      script:
        - nvm install $NODE_VERSION
        - npm install --prefix assets
        - npm run --prefix assets lint
        - npm run --prefix assets test
